model_name=TimesNet


python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay2_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \


python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay3_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay4_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 4 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay5_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 5 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay6_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 6 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/antigone/cluster-trace-predict/ClusterTracePredictModule/dataset/cluster_trace_2018/statisticsByCoreTimePreFrame/\
  --data_path dataSampleFrame25s/task_type1_CTPF_10_60.csv  \
  --model_id t1_25_CTPF_topk_5_elay7_pre1 \
  --model $model_name \
  --data CT2018 \
  --features S \
  --seq_len  16\
  --label_len 16 \
  --pred_len 1 \
  --e_layers 7 \
  --d_layers 1 \
  --factor 3 \
  --inverse \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 \
  --target 'count' \
  --freq 's' \
  --batch_size 64 \
